"""In-memory representation and textual syntax of the *Functional TPU* dialect.

The dialect is intentionally a thin bridge between StableHLO and
`Functional_TPU_ISA_v0.2.md` machine code: every operation here corresponds 1:1
to a single ISA instruction. There are no operations that are "synthesized away"
during assembly -- shape-only StableHLO ops (reshape/transpose) are folded by the
legalization pass before they ever reach this dialect, so the assembler can walk
the op list and emit one instruction per op.

The textual form is deliberately MLIR-like so it reads as a real dialect, but it
is parsed/printed by this module rather than by the MLIR C++ infrastructure (see
`src/MLIR/README.md` for why v0.1 implements the dialect in Python).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field


def shape_to_str(shape: list[int]) -> str:
    """Render a shape as the dialect's `RxC` (or `N`) token."""
    return "x".join(str(d) for d in shape) if shape else "1"


def parse_shape(token: str) -> list[int]:
    """Parse a dialect shape token (`1x4`, `4`, ...) into a list of ints."""
    return [int(d) for d in token.split("x")]


@dataclass
class Operand:
    """A value reference plus the dimensions it is used with at this op.

    `name` is the SSA name (e.g. `%arg0` for a weight/input, or `%3` for a prior
    result). `shape` is the shape as seen by the consuming instruction, which may
    differ from the value's original shape because reshapes were folded in.
    """

    name: str
    shape: list[int]


@dataclass
class MultOp:
    """Matrix multiply -> ISA `mult` (MUL format)."""

    result: str
    lhs: Operand
    rhs: Operand
    out_shape: list[int]


@dataclass
class AddOp:
    """Elementwise add -> ISA `add` (ELEM format)."""

    result: str
    lhs: Operand
    rhs: Operand
    out_shape: list[int]


@dataclass
class ReluOp:
    """Rectified linear unit -> ISA `relu` (ACT format)."""

    result: str
    src: Operand
    length: int


@dataclass
class ReturnOp:
    """Marks the program's output value. Emits no instruction itself."""

    value: str
    shape: list[int]


@dataclass
class EndOp:
    """Program terminator -> ISA `end` (SYSTEM format)."""


@dataclass
class Program:
    """A whole TPU dialect program (one `tpu.func`)."""

    name: str
    ops: list = field(default_factory=list)


def serialize(program: Program) -> str:
    """Render a `Program` to its textual `.tpu.mlir` form."""
    lines: list[str] = [
        "// Functional TPU dialect (v0.1) -- generated by the legalization pass.",
        "// Each tpu.* op maps 1:1 to a Functional_TPU_ISA_v0.2 instruction.",
        f"module @{program.name} {{",
        "  tpu.func @main {",
    ]
    for op in program.ops:
        lines.append("    " + _serialize_op(op))
    lines.append("  }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _serialize_op(op) -> str:
    if isinstance(op, MultOp):
        return (
            f"{op.result} = tpu.mult {op.lhs.name} : {shape_to_str(op.lhs.shape)}, "
            f"{op.rhs.name} : {shape_to_str(op.rhs.shape)} -> {shape_to_str(op.out_shape)}"
        )
    if isinstance(op, AddOp):
        return (
            f"{op.result} = tpu.add {op.lhs.name} : {shape_to_str(op.lhs.shape)}, "
            f"{op.rhs.name} : {shape_to_str(op.rhs.shape)} -> {shape_to_str(op.out_shape)}"
        )
    if isinstance(op, ReluOp):
        return f"{op.result} = tpu.relu {op.src.name} : {op.length} -> {op.length}"
    if isinstance(op, ReturnOp):
        return f"tpu.return {op.value} : {shape_to_str(op.shape)}"
    if isinstance(op, EndOp):
        return "tpu.end"
    raise AssertionError(f"Cannot serialize unknown TPU op: {op!r}")


_SSA = r"%[\w\.]+"
_SHAPE = r"[\dx]+"

_MULT_RE = re.compile(
    rf"({_SSA})\s*=\s*tpu\.mult\s+({_SSA})\s*:\s*({_SHAPE})\s*,\s*"
    rf"({_SSA})\s*:\s*({_SHAPE})\s*->\s*({_SHAPE})"
)
_ADD_RE = re.compile(
    rf"({_SSA})\s*=\s*tpu\.add\s+({_SSA})\s*:\s*({_SHAPE})\s*,\s*"
    rf"({_SSA})\s*:\s*({_SHAPE})\s*->\s*({_SHAPE})"
)
_RELU_RE = re.compile(
    rf"({_SSA})\s*=\s*tpu\.relu\s+({_SSA})\s*:\s*(\d+)\s*->\s*(\d+)"
)
_RETURN_RE = re.compile(rf"tpu\.return\s+({_SSA})\s*:\s*({_SHAPE})")
_MODULE_RE = re.compile(r"module\s+@([\w\.]+)")


def parse_program(text: str) -> Program:
    """Parse textual `.tpu.mlir` into a `Program`.

    Lines that are comments, braces, or the `tpu.func` header are skipped; every
    other non-blank line must match a known op or it is a hard error -- silently
    dropping an unrecognized op would produce a program that does not match the
    source graph.
    """
    module_match = _MODULE_RE.search(text)
    name = module_match.group(1) if module_match else "module"
    program = Program(name=name)

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("//"):
            continue
        if line.startswith("module") or line.startswith("tpu.func") or line in {"}", "{"}:
            continue

        op = _parse_op(line)
        assert op is not None, f"Unrecognized TPU dialect line: {raw_line!r}"
        program.ops.append(op)

    return program


def _parse_op(line: str):
    m = _MULT_RE.match(line)
    if m:
        res, a, a_sh, b, b_sh, out = m.groups()
        return MultOp(res, Operand(a, parse_shape(a_sh)), Operand(b, parse_shape(b_sh)), parse_shape(out))

    m = _ADD_RE.match(line)
    if m:
        res, a, a_sh, b, b_sh, out = m.groups()
        return AddOp(res, Operand(a, parse_shape(a_sh)), Operand(b, parse_shape(b_sh)), parse_shape(out))

    m = _RELU_RE.match(line)
    if m:
        res, src, in_len, out_len = m.groups()
        assert in_len == out_len, f"relu length mismatch on line: {line!r}"
        return ReluOp(res, Operand(src, [int(in_len)]), int(in_len))

    m = _RETURN_RE.match(line)
    if m:
        val, sh = m.groups()
        return ReturnOp(val, parse_shape(sh))

    if line == "tpu.end":
        return EndOp()

    return None
