// Functional TPU dialect (v0.1) -- generated by the legalization pass.
// Each tpu.* op maps 1:1 to a Functional_TPU_ISA_v0.2 instruction.
module @jit_func {
  tpu.func @main {
    %1 = tpu.mult %arg4 : 1x1, %arg0 : 1x4 -> 1x4
    %3 = tpu.add %arg1 : 1x4, %1 : 1x4 -> 1x4
    %5 = tpu.mult %3 : 1x4, %arg2 : 4x1 -> 1x1
    %7 = tpu.add %arg3 : 1x1, %5 : 1x1 -> 1x1
    tpu.return %7 : 1x1
    tpu.end
  }
}
