// Functional TPU dialect (v0.3) -- generated by the legalization pass.
// Each tpu.* op maps 1:1 to a Functional_TPU_ISA instruction.
module @jit_func {
  tpu.func @main {
    %1 = tpu.mult %arg4 : 1x1, %arg0 : 1x4 -> 1x4 {M0 = 223, n = 15}
    %5 = tpu.mult %1 : 1x4, %arg2 : 4x1 -> 1x1 {M0 = 145, n = 15}
    tpu.return %5 : 1x1
    tpu.end
  }
}
